from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    """
    Pydantic request schema for the /query REST endpoint.
    """
    question: str = Field(
        ...,
        min_length=3,
        description="The user's technical question.",
        examples=["How do I create a POST endpoint in FastAPI?"]
    )
    top_k: Optional[int] = Field(
        default=None,
        ge=1,
        le=20,
        description="Optional override for final top-K re-ranked context count."
    )


class SourceAttribution(BaseModel):
    """
    Schema representing source attribution metadata for a retrieved document chunk.
    """
    source: str = Field(..., description="File system path of the source document.")
    file_name: str = Field(..., description="Filename of the source document.")
    chunk_id: str = Field(..., description="Unique chunk identifier.")
    score: float = Field(..., description="Cross-encoder relevance score.")


class ContextChunkInfo(BaseModel):
    """
    Schema representing retrieved context chunk payload.
    """
    chunk_id: str = Field(..., description="Unique chunk identifier.")
    content: str = Field(..., description="Text content of the chunk.")
    score: float = Field(..., description="Relevance score.")


class LatencyBreakdown(BaseModel):
    """
    Latency metrics in milliseconds.
    """
    retrieval: float = Field(..., description="FAISS candidate search latency (ms).")
    reranking: float = Field(..., description="Cross-encoder re-ranking latency (ms).")
    generation: float = Field(..., description="LLM generation latency (ms).")
    total: float = Field(..., description="Total end-to-end pipeline latency (ms).")


class QueryResponse(BaseModel):
    """
    Pydantic response schema for the /query REST endpoint.
    """
    question: str = Field(..., description="Original question submitted by user.")
    answer: str = Field(..., description="Grounded technical answer generated by LLM.")
    sources: List[SourceAttribution] = Field(..., description="List of source document citations.")
    retrieved_context: List[ContextChunkInfo] = Field(..., description="Retrieved context chunks used for grounding.")
    latency_ms: LatencyBreakdown = Field(..., description="Component latency breakdown in milliseconds.")


class HealthResponse(BaseModel):
    """
    System health status response.
    """
    status: str = Field(..., examples=["ok"])
    environment: str = Field(..., examples=["development"])
    indexed_vectors: int = Field(..., description="Number of vectors in FAISS index.")


class SystemStatsResponse(BaseModel):
    """
    System configuration stats response.
    """
    embedding_model: str
    reranker_model: str
    llm_model: str
    retrieval_top_k: int
    rerank_top_k: int
    total_indexed_chunks: int