from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=3,
        description="The user's technical question.",
        examples=["How do I create a POST endpoint in FastAPI?"]
    )
    top_k: Optional[int] = Field(
        default=None,
        ge=1,
        le=20,
        description="Optional override for final top-K re-ranked context count."
    )


class SourceAttribution(BaseModel):
    source: str = Field(..., description="Source document name.")
    file_name: str = Field(..., description="Filename of the source document.")
    chunk_id: str = Field(..., description="Unique chunk identifier.")
    score: float = Field(..., description="Cross-encoder relevance score.")


class ContextChunkInfo(BaseModel):
    chunk_id: str = Field(..., description="Unique chunk identifier.")
    content: str = Field(..., description="Text content of the chunk.")
    score: float = Field(..., description="Relevance score.")


class LatencyBreakdown(BaseModel):
    retrieval: float = Field(..., description="FAISS candidate search latency (ms).")
    reranking: float = Field(..., description="Cross-encoder re-ranking latency (ms).")
    generation: float = Field(..., description="LLM generation latency (ms).")
    total: float = Field(..., description="Total end-to-end pipeline latency (ms).")


class QueryResponse(BaseModel):
    question: str = Field(..., description="Original question submitted by user.")
    answer: str = Field(..., description="Grounded technical answer generated by LLM.")
    sources: List[SourceAttribution] = Field(..., description="List of source document citations.")
    retrieved_context: List[ContextChunkInfo] = Field(..., description="Retrieved context chunks used for grounding.")
    latency_ms: LatencyBreakdown = Field(..., description="Component latency breakdown in milliseconds.")
    retrieved_candidate_count: int = Field(default=0, description="Raw candidates fetched during dense retrieval.")
    selected_chunk_count: int = Field(default=0, description="Final context chunks supplied to the prompt.")


class SubsystemHealth(BaseModel):
    status: str = Field(..., examples=["ok", "degraded", "error"])
    details: Optional[str] = Field(default=None)


class HealthResponse(BaseModel):
    status: str = Field(..., examples=["ok", "degraded", "error"])
    environment: str = Field(..., examples=["production"])
    indexed_vectors: int = Field(..., description="Number of vectors in FAISS index.")
    subsystems: Dict[str, SubsystemHealth] = Field(..., description="Individual subsystem health metrics.")


class SystemStatsResponse(BaseModel):
    embedding_model: str
    reranker_model: str
    llm_model: str
    retrieval_top_k: int
    rerank_top_k: int
    total_indexed_chunks: int